// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: orders-pkg-models.proto

package orders_pkg

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Order struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderUuid     []byte                 `protobuf:"bytes,1,opt,name=order_uuid,json=orderUuid,proto3" json:"order_uuid,omitempty"`
	UserUuid      []byte                 `protobuf:"bytes,2,opt,name=user_uuid,json=userUuid,proto3" json:"user_uuid,omitempty"`
	OrderStatus   int64                  `protobuf:"varint,3,opt,name=order_status,json=orderStatus,proto3" json:"order_status,omitempty"`
	Params        *Params                `protobuf:"bytes,4,opt,name=params,proto3" json:"params,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Order) Reset() {
	*x = Order{}
	mi := &file_orders_pkg_models_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_orders_pkg_models_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_orders_pkg_models_proto_rawDescGZIP(), []int{0}
}

func (x *Order) GetOrderUuid() []byte {
	if x != nil {
		return x.OrderUuid
	}
	return nil
}

func (x *Order) GetUserUuid() []byte {
	if x != nil {
		return x.UserUuid
	}
	return nil
}

func (x *Order) GetOrderStatus() int64 {
	if x != nil {
		return x.OrderStatus
	}
	return 0
}

func (x *Order) GetParams() *Params {
	if x != nil {
		return x.Params
	}
	return nil
}

type Orders struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Orders        []*Order               `protobuf:"bytes,1,rep,name=Orders,proto3" json:"Orders,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Orders) Reset() {
	*x = Orders{}
	mi := &file_orders_pkg_models_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Orders) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Orders) ProtoMessage() {}

func (x *Orders) ProtoReflect() protoreflect.Message {
	mi := &file_orders_pkg_models_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Orders.ProtoReflect.Descriptor instead.
func (*Orders) Descriptor() ([]byte, []int) {
	return file_orders_pkg_models_proto_rawDescGZIP(), []int{1}
}

func (x *Orders) GetOrders() []*Order {
	if x != nil {
		return x.Orders
	}
	return nil
}

type Params struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Params        []*Param               `protobuf:"bytes,1,rep,name=Params,proto3" json:"Params,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Params) Reset() {
	*x = Params{}
	mi := &file_orders_pkg_models_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Params) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Params) ProtoMessage() {}

func (x *Params) ProtoReflect() protoreflect.Message {
	mi := &file_orders_pkg_models_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Params.ProtoReflect.Descriptor instead.
func (*Params) Descriptor() ([]byte, []int) {
	return file_orders_pkg_models_proto_rawDescGZIP(), []int{2}
}

func (x *Params) GetParams() []*Param {
	if x != nil {
		return x.Params
	}
	return nil
}

type Param struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MealUuid      []byte                 `protobuf:"bytes,1,opt,name=meal_uuid,json=mealUuid,proto3" json:"meal_uuid,omitempty"`
	DeliveryUuid  []byte                 `protobuf:"bytes,2,opt,name=delivery_uuid,json=deliveryUuid,proto3" json:"delivery_uuid,omitempty"`
	Date          int64                  `protobuf:"varint,3,opt,name=date,proto3" json:"date,omitempty"`
	Quantity      int64                  `protobuf:"varint,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Param) Reset() {
	*x = Param{}
	mi := &file_orders_pkg_models_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Param) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Param) ProtoMessage() {}

func (x *Param) ProtoReflect() protoreflect.Message {
	mi := &file_orders_pkg_models_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Param.ProtoReflect.Descriptor instead.
func (*Param) Descriptor() ([]byte, []int) {
	return file_orders_pkg_models_proto_rawDescGZIP(), []int{3}
}

func (x *Param) GetMealUuid() []byte {
	if x != nil {
		return x.MealUuid
	}
	return nil
}

func (x *Param) GetDeliveryUuid() []byte {
	if x != nil {
		return x.DeliveryUuid
	}
	return nil
}

func (x *Param) GetDate() int64 {
	if x != nil {
		return x.Date
	}
	return 0
}

func (x *Param) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

var File_orders_pkg_models_proto protoreflect.FileDescriptor

const file_orders_pkg_models_proto_rawDesc = "" +
	"\n" +
	"\x17orders-pkg-models.proto\x12\x06models\"\x8e\x01\n" +
	"\x05Order\x12\x1d\n" +
	"\n" +
	"order_uuid\x18\x01 \x01(\fR\torderUuid\x12\x1b\n" +
	"\tuser_uuid\x18\x02 \x01(\fR\buserUuid\x12!\n" +
	"\forder_status\x18\x03 \x01(\x03R\vorderStatus\x12&\n" +
	"\x06params\x18\x04 \x01(\v2\x0e.models.ParamsR\x06params\"/\n" +
	"\x06Orders\x12%\n" +
	"\x06Orders\x18\x01 \x03(\v2\r.models.OrderR\x06Orders\"/\n" +
	"\x06Params\x12%\n" +
	"\x06Params\x18\x01 \x03(\v2\r.models.ParamR\x06Params\"y\n" +
	"\x05Param\x12\x1b\n" +
	"\tmeal_uuid\x18\x01 \x01(\fR\bmealUuid\x12#\n" +
	"\rdelivery_uuid\x18\x02 \x01(\fR\fdeliveryUuid\x12\x12\n" +
	"\x04date\x18\x03 \x01(\x03R\x04date\x12\x1a\n" +
	"\bquantity\x18\x04 \x01(\x03R\bquantityB\x16Z\x14protocols/orders-pkgb\x06proto3"

var (
	file_orders_pkg_models_proto_rawDescOnce sync.Once
	file_orders_pkg_models_proto_rawDescData []byte
)

func file_orders_pkg_models_proto_rawDescGZIP() []byte {
	file_orders_pkg_models_proto_rawDescOnce.Do(func() {
		file_orders_pkg_models_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_orders_pkg_models_proto_rawDesc), len(file_orders_pkg_models_proto_rawDesc)))
	})
	return file_orders_pkg_models_proto_rawDescData
}

var file_orders_pkg_models_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_orders_pkg_models_proto_goTypes = []any{
	(*Order)(nil),  // 0: models.Order
	(*Orders)(nil), // 1: models.Orders
	(*Params)(nil), // 2: models.Params
	(*Param)(nil),  // 3: models.Param
}
var file_orders_pkg_models_proto_depIdxs = []int32{
	2, // 0: models.Order.params:type_name -> models.Params
	0, // 1: models.Orders.Orders:type_name -> models.Order
	3, // 2: models.Params.Params:type_name -> models.Param
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_orders_pkg_models_proto_init() }
func file_orders_pkg_models_proto_init() {
	if File_orders_pkg_models_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_orders_pkg_models_proto_rawDesc), len(file_orders_pkg_models_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_orders_pkg_models_proto_goTypes,
		DependencyIndexes: file_orders_pkg_models_proto_depIdxs,
		MessageInfos:      file_orders_pkg_models_proto_msgTypes,
	}.Build()
	File_orders_pkg_models_proto = out.File
	file_orders_pkg_models_proto_goTypes = nil
	file_orders_pkg_models_proto_depIdxs = nil
}
